version: '3.7'

services:
  playground-server:
    container_name: playground-server
    image: squaaat/playground-server:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: "/playground"
    ports:
      - "3000:3000"

  playground-mysql:
    image: mysql:latest
    ports:
      - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysql
